name: jpstrack

description: GPX-tracking GPS App for creating OpenStreetMap/Google Earth data

publish_to: 'none' # This is an app, not a library, so don't publish as lib

version: 2.0.2+202

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_links: ^6.3.1
  app_settings: ^6.1.1
  cached_network_image: ^3.4.0
  flutter_map: ^8.2.1
  flutter_settings_screens: ^0.3.4
  flutter_widget_from_html: ^0.17.0
  geolocator: ^14.0.2
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  latlong2: any
  location: ^8.0.1
  oauth2: ^2.0.3
  path_provider: ^2.0.6
  path: any
  record: ^6.1.1
  shared_preferences: any
  sqflite: ^2.0.0+4
  url_launcher: ^6.3.0
  xml: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo.png

flutter_icons:
  android: true
  ios: true
  remove-alpha_ios: true
  image_path: "images/icon.png"

flutter_intl:
  enabled: true
