name: jpstrack

description: GPX-tracking GPS App for creating OpenStreetMap/Google Earth data

publish_to: 'none' # This is an app, not a library, so don't publish as lib

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  cached_network_image: any
  flutter_map: ^7.0.2
  flutter_settings_screens: ^0.3.4
  flutter_widget_from_html: ^0.15.1
  geolocator: ^12.0.0
  image_picker: ^1.1.2
  latlong2: any
  location: ^7.0.0
  path_provider: ^2.0.6
  record: ^5.1.2
  sqflite: ^2.0.0+4
  url_launcher: ^6.3.0
  xml: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo.png

flutter_icons:
  android: true
  ios: true
  remove-alpha_ios: true
  image_path: "images/logo.png"

flutter_intl:
  enabled: true
