name: jpstrack

description: GPX-tracking GPS App for creating OpenStreetMap/Google Earth data

publish_to: 'none' # This is an app, not a library, so don't publish as lib

version: 2.0.1+201

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.0
  flutter_map: ^7.0.2
  flutter_settings_screens: ^0.3.4
  flutter_widget_from_html: ^0.15.1
  http: ^1.2.2
  intl: ^0.19.0
  geolocator: ^12.0.0
  image_picker: ^1.1.2
  latlong2: any
  location: ^7.0.0
  path: any
  path_provider: ^2.0.6
  record: ^5.1.2
  shared_preferences: any
  sqflite: ^2.0.0+4
  url_launcher: ^6.3.0
  xml: any
  app_settings: ^5.1.1
  oauth2: ^2.0.3
  app_links: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo.png

flutter_icons:
  android: true
  ios: true
  remove-alpha_ios: true
  image_path: "images/icon.png"

flutter_intl:
  enabled: true
