= jpstrack: a Map Maker's Data Gatherer

JpsTrack is a Map Maker application,
a GPX-tracking GPS App for creating OpenStreetMap or Google Earth data.
This is _not_ a navigation app for getting from point A to point B;
there are better tools for that in almost any app store.

== History

I wrote the first version of jpsTrack in 2007 as a Java SE application.
A few years after that - starting in 2010 - I wrote an Android user interface,
also in Java. I named this version 'jpstrack.android', and it went into the
Google Play store with that name.

Fast-forward a decade and a half, and it was time for a rewrite.
This is an all-new implementation in Flutter, to run on both Android and iOS.
Android users were updated automatically from the old version
to this one, but for that to work I had to keep the old version's name,
so it's still called "jpstrack.android" even though written in Flutter.

The app is written entirely in Flutter. GitHub shows HTML as a big chunk
of the code simply because I keep the website in the same repo as the code.
"So there we were, all in one place, A generation Lost In Space..."

The minimum version for the Android version is now API 23 (Android 6).
This goes up all the time.

== Building

If you just want to _use_ this app, there' no need to build it!
Just visit https://play.google.com/store/apps/details?id=jpstrack.android[]
in your Android phone's browser.

I will put this app into the Apple Store as well once I get the OAUTH2 working.

But if you do want to build it, you can either open it as a project in Android Studio,
or from the command line, cd into the top level and type `flutter run` or `flutter build`.
The latter will need some argument(s), but the help will guide you (try 'apk' for Android).

== ToDo

Such apps are never complete. Here are some things that need doing:

=== Short Term

Get OAUTH2 working reliably.

Track class:
	Prompt for a comment when uploading, save with Track in case upload fails.
	Add an uploaded_date field.

=== Next Version

SETTINGS
	Add "seconds interval" and "min distance"
	Show/hide password

YT video for 2.0.1 https://youtu.be/VNkTrJkEVDU

=== After That

Roll out to iOS.

Deal better with the zoom ratio?

Voice note: transcribe, using https://github.com/MarcusNg/flutter_voice ?

