= jpstrack

JpsTrack is a Map Maker application,
a GPX-tracking GPS App for creating OpenStreetMap or Google Earth data
This program is not a navigation app for getting from point A to point B.

== History

I wrote the first version of jpsTrack in 2007 as a Java SE application.
A few years after that - starting in 2010 - I wrote an Android user interface,
also in Java.

This is an all-new implementation in Flutter, to run on both Android and iOS.
Android users will be updated automatically from the old version
to this one, once it gets into the play store.

The minimum version of Android is now API 23 (Android 6).

== ToDo

Such apps are never complete. Here are some things that need doing:

=== Short Term

Don't recreate authentication (use from osm_upload.dart?)

Prompt for a comment when uploading, save with Track in case upload fails.

Track: have an uploaded_date field.

Move Menu to right side, in Export page.

Export: Use getExternalStorageDirectory on Android, getApplicationStorage on iOS.

=== Next Version

TBA

=== After That

Roll out to iOS.

Deal better with the zoom ratio?

Voice note: transcribe, using https://github.com/MarcusNg/flutter_voice ?

