= jpstrack

JpsTrack is a Map Maker application,
a GPX-tracking GPS App for creating OpenStreetMap or Google Earth data
This program is not a navigation app for getting from point A to point B.

== History

I wrote the first version of jpsTrack in 2007 as a Java SE application.
A few years after that - starting in 2010 - I wrote an Android user interface,
also in Java. I named this version 'jpstrack.android', and it went into the
Google Play store with that name.

Fast-forward a decade and a half, and it was time for a rewrite.
This is an all-new implementation in Flutter, to run on both Android and iOS.
Android users were updated automatically from the old version
to this one, but for that to work I had to keep the old version's name,
so it's still called "jpstrack.android" even though written in Flutter.

The minimum version of Android is now API 23 (Android 6).

== ToDo

Such apps are never complete. Here are some things that need doing:

=== Short Term

Get OAUTH2 working reliably.

Export tracks must be to a non-root-private directory.
Export: Use getExternalStorageDirectory on Android, getApplicationStorage on iOS.

Track class:
	Prompt for a comment when uploading, save with Track in case upload fails.
	Add an uploaded_date field.

Move Menu to right side, in Export page.

=== Next Version

TBA

SETTINGS
	Add "seconds interval" and "min distance"
	Show/hide password

YT video for 2.0.1 https://youtu.be/VNkTrJkEVDU

=== After That

Roll out to iOS.

Deal better with the zoom ratio?

Voice note: transcribe, using https://github.com/MarcusNg/flutter_voice ?

