= JPSTrack, a GPS/GPX Tracker

Not the kind of "tracker" you use to find whether or where your spouse is cheating.
This program collects mapping data for inclusion into
https://www.openstreetmap.org/[OpenStreetMap] (the free, editable map of the world),
https://www.google.com/maps/about/mymaps/[Google Maps],
or any other application that can import GPX-format track data.

[CAUTION]
====
This app uses the "background location" feature to
keep tracking while in the background, e.g., if you get a phone call
or send a text while creating a track.  _Be aware that the app will keep
tracking your movements_ until you click the Stop (or Pause) buttons.
====

[CAUTION]
====
Android users: Note that if you don't give the app Background Location permission, it will stop getting updates
as soon as you switch to any other app for any reason, or even if your screen blank timeout kicks in.
You really need to grant this permission.
====

[CAUTION]
====
While in motion (walking, cycling, driving, etc.), please pay attention
to the world around you, not to your device.
If you get run over by a truck or drive off a cliff or step in front of a moving train,
your map data will probably never get used.
And the author of this app accepts no responsibility for whatever happens when you're using it.
====

This is NOT a route-from-here-to-there Navigation application (there are many of those
in the app stores already). 
Also, it does NOT try to be an OSM editor. In the author's
experience, most current Android devices do not have the I/O capability
to do this job well. I recommend uploading the files 
to a desktop PC and runnnig the JOSM editor or
using the web-based editor on the OSM site.

JPSTrack differs from Google's own My Tracks in that it is much more
narrowly focused: it only records GPX tracks for OSM. It allows you to
upload GPX tracks directly to OSM.

The program collects data once you press the Start button, and goes
until you PAUSE or SAVE. PAUSE can be resumed with the RESUME button.
The SAVE button ends a run and closes the file.

There is also voice notes, text notes, and pictures. All are saved,
along with the GPX files, in your device's external storage, commonly
/sdcard/jpstrack.android (and changeable in Preferences).

The name is historical; the program was originally written in
link:/java[Java], and the name 'gpstrack' was already in use by another
program.

== Feedback/Support

Always welcome. Please email jpstrack-feedback@darwinsys.com.

JpsTrack runs on most every Android device out there, except for
the very oldest ones.

This is an early release of the software; please see the
link:RELEASE_NOTES.txt[Release Notes] before you decide it's buggy; we
know about most of the bugs that are in this version and will fix them
as we have time...

== Where?

You can get the current stable version for Android from 
https://play.google.com/store/apps/details?id=jpstrack.android[Google Play].

== OSM Wiki

There is also a JPSTrack page at the
https://wiki.openstreetmap.org/wiki/Jpstrack[OpenStreetMap Wiki].

== Source Code?

This is a free and open source application. Source is provided for most
uses, but you may not distribute the app back to Google Play Store or
other market, as that would lead to fragmentation. Code is at
https://github.com/IanDarwin; you need the two repos _jpstrack_ and
_jpstrack.android_.

*Why two source modules?* Each module is a separate project. The code is based
on an earlier JavaSE version of jpstrack. Since (prior to the move to IntelliJ/Android Studio)
you couldn't really have
both a JavaSE and an Android project in the same project, and
since I refuse to copy-and-paste entire files, I left the original and
just refer to it.
The _jpstrack_ module contains the code for saving in GPX format.
There is a Maven _pom.xml_ file in jpstrack to produce the required jar file.
Since this isn't worth the trouble of publishing on Maven Central, just copy
the jar file into the lib folder of the jpstrack.android project.
