= jpstrack, the Open Streetmap and GPX data collector

== Version 2.0.1

Minor fix release after 2.0.0: Show Export page when you Stop recording a track.
Shows the Welcome web page with important disclaimers the first time you run this version.

== Version 2.0.0 "New Again"

Complete rewrite in Flutter, so we can run on iOS as well as Android.
Addresses newer Android releases, as required by Google Play.

UI is significantly improved, and much more modern.

Uploading to OSM is temporarily disabled, as OSM recently completely
changed their authentication mechanism (from "BASIC" to "OAUTH2")
and we haven't caught up. However, tracks are saved in an SQLITE3
database on-device and can be saved to a file; either form will 
be uploadable in the next revision, due in a few weeks.

Buglet: after taking a picture, due to an issue with the photo library
we're using, the "checkbox" button appears black-on-black on some devices.
Just tap in the lower right of the screen to make the checkbox appear,
or the lower left to cancel it.

== Version 1.1.0 - 2024-07-15

No significant changes, but MINSDK is now 21 (Android 5!)
Release primarily to address new Android versions.

This version is still written in Java for the Android SDK.
The next version will be written in Flutter, which would allow
the app to also appear on the Apple App Store. 

== Version 1.0.4 - early 2020s, not released.

== Version 1.0.0 - 2014-04-15

UI updated with Android ActionBar. I still support phones as far back as API
Level 7 (had to move up from 6 to get the support library for the ActionBar;
sorry to both of you that still run Android 1.6 devices).

Enables auto-loading. Set your OSM username/email in Preferences and enable Auto-Upload.
When you save a reading, you'll be asked to confirm (and enter your password if it's
the first upload of this invocation; we only store the password in memory for security
reasons; OAuth2.x coming later).

Fixes a bug that caused the app to stop recording when the phone went idle.

Prevent using back button during voice recording, as this leaves the recorder
in a confused state.

Further small changes to the XML detected when auto-loading was
enabled. Traces now get uploaded and import successfully.

There is a proper buglist in a database on our server, although it's not yet
web-accessible, so your suggestions are being saved and acted upon.

== Version 0.8 - 2014-01-27

Minor bug fix and enhancements.

Fixes a bug in the generated XML that caused strict XML parsers used
in some third-party software to reject the GPX files.

Fixes a bug that would occasionally cause a crash if you rotated the 
device while recording GPS.

Version 0.7 - first release to the Android Play Store and BlackBerry World.

This is a Beta release. Please note the following:

- We try to ensure that the GPX file is closed correctly, but this
  does not always happen. If your destination app cannot read the file,
  try opening it with a plain-text editor (good ole vi!) and add
  these three "end tag" lines after the last end-trackpoint (</trkpt>) tag.
    </trkseg>
	</trk>
	</gpx>
	
- Do NOT use the application with the USB connected and the SDCard
  exported to your desktop, on platforms where this disables all
  Android Apps's access to the /sdcard folder, as there may be
  some places where the app might crash if the /sdcard
  is not available.

- There are no language-translation files yet so the program 
  only works in English. 
  
  Hay una traduccion muy cruda para Espanol, pero se puede morir
  de reir si intenta usarlo. No pagamos las cuentas funerales que
  resultan, ni ningunas otras consecuencias. Sirvense ayudanos
  con una traduccion mas correcta?

- Voice Note files are saved as standard MP3's, but the CODEC used
  is not always available on the desktop.

- The footprint 'tracks' on the icon look more like missiles
  than the intended footprints. Somebody with a bit more
  artist-fu should work on them.

If you find any new ways to crash it, please email or use this:

https://darwinsys.com/contact
